# Spawns solely the API's associated services in docker containers

version: "3.9"
services:
  # The Database
  postgres:
    # Basics
    image: postgres

    # Port Mapping
    ports:
      - "5432:5432"

    # Volumes/Data Store
    volumes:
      - ../postgres-data:/var/lib/postgresql/data

    # Env Vars
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
